services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/disk1/.beszel:/extra-filesystems/sda1:ro
      - /mnt/disk2/.beszel:/extra-filesystems/sdb1:ro
      - /mnt/disk3/.beszel:/extra-filesystems/sdc1:ro
      - /mnt/disk4/.beszel:/extra-filesystems/sdd1:ro
      - /mnt/disk5/.beszel:/extra-filesystems/sde1:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "add-key-here"